theme: jekyll-theme-minimal
title: Eveline Band | Electronic Press Kit
description: Landing Page resume about the Italian Alternative Metal Band

lsi: false
safe: true
source: [E:\EVE Epk Github\]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
